### ISSUE TITLE
Wakeword agent has unmet dependency on WiringPi

### ISSUE THREAD

**Issue by hex4def6** [alexa/alexa-avs-sample-app#416]
While running the installer, I get the following issue:

```
[ 60%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp:6:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
CMakeFiles/wakeWordAgentTest.dir/build.make:326: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgentTest.dir/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/GPIOWakeWordEngine.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

=============================
*****************************
========= Finished ==========
*****************************
=============================


```

This is because I do not have WiringPi (fresh raspbian install).  After installing WiringPi, it works correctly.

**Comment by GenericUK** [comment]
How did you install WiringPi?

**Comment by rrbutani** [comment]
@GenericUK `sudo apt-get install wiringpi`

**Comment by soswow** [comment]
Shouldn't this part of overall automated_install script?

**Comment by kerrongordon** [comment]
i got wiringpi install and working on ubuntu 16.04 with this information [wiringpi](http://wiringpi.com/download-and-install/)

```
git clone git://git.drogon.net/wiringPi
cd ~/wiringPi
./build
```

**Comment by koolkarni** [comment]
If wiringPI is not getting installed on Arm linux then you can install wiringX
