### ISSUE TITLE
No pop up message to obtain tokens

### ISSUE THREAD

**Issue by jdmeissner** [alexa/alexa-avs-sample-app#1093]
The "Alexa Voice Service - v20160207.7" window loads with "Login" clickable, but the expected pop-up to obtain tokens does not appear.  I am pretty confident that I set the product ID, client id etc correctly.

Installation on Fedora 27
Java Version 1.8.0-162
Node.js Version 8.9.3
Apache Maven Version 3.5.2
alpn-boot-version is set to 8.1.11.v20170118 in pom.xml
(this seems to be the highest version, corresponding with open-jdk v. 1.8.0u152, which is the latest entry on http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions)

`npm start` seems to work fine: "Listening on port 3000"

`mvn validate` reports "Build Success"

`mvn install` generates a few warnings, shown below, but I thought to be irrelevant:

```
[INFO] Scanning for projects...
[INFO] 

[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sample-java-client ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!

[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] Copying 5 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sample-java-client ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sample-java-client ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/jdm/Documents/alexa-avs-sample-app/samples/javaclient/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ sample-java-client ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ sample-java-client ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sample-java-client ---
[INFO] Building jar: /home/jdm/Documents/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.7.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ sample-java-client ---
[INFO] Installing /home/jdm/Documents/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.7.jar to /home/jdm/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.7/sample-java-client-20160207.7.jar
[INFO] Installing /home/jdm/Documents/alexa-avs-sample-app/samples/javaclient/pom.xml to /home/jdm/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.7/sample-java-client-20160207.7.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.545 s
[INFO] Finished at: 2018-01-17T17:12:47-05:00
[INFO] Final Memory: 12M/163M
[INFO] ------------------------------------------------------------------------
```

`mvn exec:exec`  starts the Alexa window, but generates these messages:

```
jdm@localhost javaclient]$ mvn exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-23" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1087)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:224)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:157)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(AuthSetup.java:90)
	at java.lang.Thread.run(Thread.java:748)
```
Any help would be greatly appreciated.

**Comment by JohannesKlauss** [comment]
I got the same issue under Windows 10:

```
D:\projects\alexa-avs-sample-app\samples\javaclient>mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Qt: Untested Windows version 10.0 detected!
Exception in thread "Thread-28" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1087)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:224)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:157)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(AuthSetup.java:90)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by dhpp** [comment]
Could you please look at the guidance offered under #956 and let us know if that helps?  Thanks.

**Comment by jdmeissner** [comment]
I had looked at #956 previously and believe it is not related.  The solution suggested to downgrade the RPI linux OS.  I am running Fedora 27 on a laptop.  The error message seems to be different as well: Exception in thread "Thread-23" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension

**Comment by bandkenamazoncom** [comment]
What version of the JDK are you using?

Please see if this is what you are running into: https://github.com/alexa/alexa-avs-sample-app/issues/520

**Comment by BennyAvramson** [comment]
Hi @jdmeissner, @JohannesKlauss,

The Jetty table we refer to for the `alpn-boot.version` value in the `pom.xml` is not updated yet with the correct value for JDK 1.8.0.161 and 1.8.0.162. We have the same issue with the JSA installation script for Pi.

We'll update the installation guide with this and fix the Pi script on the coming release.

Meantime, you can fix the issue by putting `8.1.12.v20180117` as `alpn-boot.version` value.
Pi users should do this fix **after** running the install script. The file to fix is `pom.xml`.

Please let me know if that worked for you.

**Comment by khassel** [comment]
works with JDK 1.8.0.161 
Thank you!

**Comment by jdmeissner** [comment]
Thank you @BennyAvramson,  changing `alpn-boot.version` value to  `8.1.12.v20180117` solved the Access Token problem for me with JDK 1.8.0.162.  
I expected the Alexa Voice Service Window to pop up afterwards.  Instead I got the output below in the console:  
```
Welcome to AVS! To interact with this app, type one of the following commands, followed by <enter>
Login/Logout: login or logout
To listen: <space>/l/listen, or just press enter!
Next song: n/next
Play/Pause: p/play/pause
Previous song: b/back
Switch locale: en-US/en-GB/de-DE/en-IN/ja-JP/en-CA
Quit: q/quit/exit
Display this help text again: h/help
```
The application crashes when I press l/listen, but I will do some  digging before I come back for help.
The specific token access problem is solved.
Thank you all for your comments.

**Comment by bandkenamazoncom** [comment]
Let's close this one.  Please open a new thread for the crashing issue.
